### ISSUE TITLE
Session error

### ISSUE THREAD

**Issue by yasirakel** [vgwidt/sumi#4]
Hi,

  I'm trying to run it on MacOS, but with no success. Database connection is working properly. Login is successful, but session is not working. I also checked the Redis server, it works fine, the user key is inserted.  What could cause the problem? How can I try.

<img width="1264" alt="Screen Shot 2023-01-02 at 22 02 13" src="https://user-images.githubusercontent.com/2187669/210270235-8569c7f5-52c2-4359-9cc0-96d86eabf313.png">

**Comment by vgwidt** [comment]
I think it’s a cookie issue.  If using non-https, most browsers these days will only allow secure cookies if using “localhost”.  You can confirm by checking the requests your browser is sending.  I’d recommend enabling https and using OpenSSL to quick generate self signed certs for testing.

**Comment by yasirakel** [comment]
Hi, @vgwidt 

Problem solved with OpenSSL. Thank you so much.
